### ISSUE TITLE
Failed to install sileo/Failed to extract bootsrrap

### ISSUE THREAD

**Issue by notgarette** [nqcshady/unc0ver-dark#27]
**Describe the bug**
When I press Jailbreak sileo fails to install or I get the error shown in the screenshot. Persists through rootFS restore.
**To Reproduce**
1. Press Jailbreak
2. ???

**Screenshots**
https://m.imgur.com/euwk8IM
(In airplane mode in the screenshot, it still happens when I’m not in airplane mode)

**Device (please complete the following information):**
 - iOS Version:  12.0.1
 - iOS Device: iPhone X
 - unc0ver Version: 1.1.3

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
I don’t know how to get these. If you let me know how, I’ll gladly upload them.

**Comment by Diatrus** [comment]
@bawblol This is a curious error, but it shouldn't be Sileo install exclusive. Try jailbreaking with tweaks turned off. I've never seen this after a rootFS.

**Comment by notgarette** [comment]
@Diatrus I’ve been jailbreaking with Tweaks off. Anyway, I just tried jailbreaking and it randomly decided to work. No clue why, but it does. Thanks for your work on Unc0ver Dark.

**Comment by Diatrus** [comment]
No problem, glad it's fixed.

**Comment by Tweaker177** [comment]
I'm getting this error with tweaks off, tweaks on, every time jailbreaking. This was present in an older version of uncover, but was fixed. Since the error is before Sileo install, still can't install Sileo, which is entire reason for using this version.

Also iPhone X, this is on 11.4... used latest app from Releases. (It said updated 20 hours ago or something like that) "Final Bug Fix" version of Unc0ver dark.

Curiously, the jailbreak still works, and all it takes is opening New Term 2, and typing "killall backbaoardd" and its fixed (but no Sileo).  If tweaks are on, and it's a "Re-jailbreak" I can just use a respring button from a pref bundle to fix tweaks not showing up.

I haven't looked at this source code at all... can Sileo be installed using commands in terminal?

**Comment by Diatrus** [comment]
@tweaker177 the README says “don’t use on iOS 11 for the moment”
