### ISSUE TITLE
If this was more like unc0ver

### ISSUE THREAD

**Issue by SarKaa** [nqcshady/unc0ver-dark#69]
This used to be a great alternative to unc0ver as it was always updated. Now, unc0ver dark is falling behind. Can you keep up with the original unc0ver. I really want iOS 12.4 support, but with sileo support

I've even thought about going to chimera, but I thought you'd update this, but no

**Comment by tealsnow** [comment]
I agree this has fallen behind a ton, I wonder if its because it has inefficient code or not well commented... on a more funny note, this is issue #69 👌

**Comment by kasti0** [comment]
Unfortunately they commented in a r/jailbreak post that they are not going to support this any further and that development will go back from time to time. (Can’t find the comment on reddit right now). IIRC they said it’s because pwn20wnd never supported/ liked the idea of unc0ver dark or something like that.

**Comment by debouncedgit** [comment]
You need to be patient. Are you in the discord? They're trying their best. 12.4 support isn't popping in the exploit and boom, they got it working. There's more work to it. Give them patience.

If you wish for it to be hurried up, go bother senpai pwn20wnd-kun

**Comment by 23Aaron** [comment]
Cannot be updated due to lack of updated unc0ver source.
